---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[chef-server-populator::default]
    attributes:
      chef_server_populator:
        clients:
          jbellone:
            client_key: foo
            admin: true
          pyanni:
            client_key: bar
            admin: true
            validator: true
          ske:
            client_key: baz
            admin: false
            validator: false
